---
- name: Deploy a jar file
  hosts: ubuntu18
  remote_user: mugdha
  tasks:
          - name: Copy jar file to home directory
            copy:
                    src: ./target/MiniProject-1.0-SNAPSHOT-jar-with-dependencies.jar
                    dest: ~/
