---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: mugdha/calculator
        source: pull
    - name: deploy docker container
      docker_container:
        image: mugdha/calculator
        name: calculator_container
        state: started
        ports:
          - "8080:80"
